### ISSUE TITLE
[Bug] Sum has default parseInt()

### ISSUE THREAD

**Issue by viters** [s-soltys/typescript-array-extensions#1]
Why do you use parseInt() inside Array.sum() if no callback is provided? To use it with doubles it is required now to do .sum(v => v). Also everything that uses .sum (like .average) also needs explicit (v => v).

**Comment by jimmytheneutrino** [comment]
This is really unexpected behaviour. And even if you know about it, it spoils the joy of using the lib.

**Comment by jimmytheneutrino** [comment]
@s-soltys Could you merge the PR, #2 ?

**Comment by s-soltys** [comment]
Merged PR #2 and republished the package. Thank you for contributing!
